BenimProjem/Areas/yonetimPaneli/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BenimProjem.Areas.yonetimPaneli.Controllers.Base;
using BenimProjem.BL.Business.Abstracts;
using BenimProjem.Entities;
using BenimProjem.Entities.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BenimProjem.Areas.yonetimPaneli.Controllers
{
    public class KategoriController : BaseController
    {
        IKategoriBusiness _kategoriBusiness;
        public KategoriController(IKategoriBusiness kategoriBusiness)
        {
            _kategoriBusiness = kategoriBusiness;
        }

        [Area("yonetimPaneli")]
        [Authorize]
        public IActionResult Index()
        {
            var kategoriler = _kategoriBusiness.Listele();
            return View(kategoriler);
        }
        public IActionResult Ekle(int? Id)
        {
            if (Id != null)
            {
                KategoriEkleVeDuzenleVM guncellenecekKategori = _kategoriBusiness.KategoriEkleDuzenleVMGetir(Id.Value);

                return View(guncellenecekKategori);
            }
            return View();

        }

        [HttpPost]
        public IActionResult Ekle(int? Id, KategoriEkleVeDuzenleVM model)
        {
            if (Id != null)
            {
                //Duzenleme
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var (sonuc, kategori) = _kategoriBusiness.Guncelle(model);
                MesajYaz(sonuc, kategori.KategoriAdi + " isimli kategori " + model.KategoriAdi + " isimiyle başarıyla değiştirilmiştir", kategori.KategoriAdi + " isimli kategori " + model.KategoriAdi + " isimli kategoriyle değiştirilirken beklenmeyen bir hata oluştu");
                return RedirectToAction("Index");
            }
            else
            {
                //Ekleme
                if (ModelState.IsValid)
                {
                    _kategoriBusiness.Ekle(model);
                    return RedirectToAction("Index");
                }
                else
                    return View();
            }
        }
        public JsonResult Sil(int id)
        {
            var (sonuc, kategori) = _kategoriBusiness.Sil(id);
            
                return Json(new {
                    result = sonuc, 
                    kategoriAdi = kategori.KategoriAdi
                });
        }

        public JsonResult SilKontrol(int Id)
        {
            List<Urun> urunListesi = _kategoriBusiness.KategoriyeGoreUrunler(Id);

            Kategori kategori = _kategoriBusiness.KategoriGetir(Id);
            
            if (urunListesi.Count > 0)
                return Json(new
                {
                    any = true,
                    urunler = urunListesi.Select(u => new
                    {
                        id = u.Id,
                        kategoriAdi = u.Kategori.KategoriAdi,
                        urunAdi = u.UrunAdi,
                        kategoriId = u.KategoriId,
                    })
                });
            else
                return Json(new {
                    kategoriAdi = kategori.KategoriAdi,
                    any = false
                });
        }
    }
}

BenimProjem/Areas/yonetimPaneli/Controllers/RoleController.cs
using BenimProjem.Areas.yonetimPaneli.Controllers.Base;
using BenimProjem.BL.Business.Abstracts;
using BenimProjem.Entities.Authentications;
using BenimProjem.Entities.ViewModels.Role;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BenimProjem.PL.Areas.yonetimPaneli.Controllers
{
    [Area("yonetimPaneli")]
    public class RoleController : BaseController
    {
        IRoleManagerBusiness _roleManagerBusiness;

        public RoleController(IRoleManagerBusiness roleManagerBusiness)
        {
            _roleManagerBusiness = roleManagerBusiness;
        }

        public IActionResult Index()
        {
            return View(_roleManagerBusiness.RolleriGetir());
        }

        public async Task<IActionResult> Sil(int Id)
        {
            var (result, role) = await _roleManagerBusiness.RoleSilAsync(Id);
            MesajYaz(result, role.Name + " isimli rol başarıyla silinmiştir.", role.Name + " isimli role silinirken beklenmeyen bir hata oluştu.");
            return RedirectToAction("Index");
        }

        public IActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Ekle(AppRoleEkleVM model)
        {
            bool result = await _roleManagerBusiness.RoleEkleAsync(model);
            MesajYaz(result, model.Name + " isimli rol başarıyla eklenmiştir", model.Name + " isimli role eklenirken beklenmeyen bir hata oluştu");
            return RedirectToAction("Index");
        }
    }
}

BenimProjem/Areas/yonetimPaneli/Controllers/UserController.cs
using BenimProjem.Areas.yonetimPaneli.Controllers.Base;
using BenimProjem.BL.Business.Abstracts;
using BenimProjem.Entities.Authentications;
using BenimProjem.Entities.ViewModels.Role;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BenimProjem.PL.Areas.yonetimPaneli.Controllers
{
    public class UserController : BaseController
    {
        IUserManagerBusiness _userManagerBusiness;

        public UserController(IUserManagerBusiness userManagerBusiness)
        {
            _userManagerBusiness = userManagerBusiness;
        }

        public IActionResult Index()
        {
            return View(_userManagerBusiness.AllUsers());
        }
        public async Task<IActionResult> DeleteUser(int Id)
        {
            var (result ,username) = await _userManagerBusiness.DeleteUser(Id);
            MesajYaz(result, username + " adlı kullanıcıı başarıyla silinmiştir", username + " adlı kullanıcı silinirken beklenmeyen bir hata oluştu ");
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> RolAta(int Id)
        {
            List<AppRoleAtaVM> roller = await _userManagerBusiness.TumRolleriGetir(Id);
            return View(roller);
        }
        [HttpPost]
        public async Task<IActionResult> RolAta(int Id, List<AppRoleAtaVM> model)
        {
            var (result, username) = await _userManagerBusiness.RolAtaveSil(Id, model);
            MesajYaz(result, username + " isimli kullanıcıya roller başarıyla atanmıştır.", username + " isimli kullanıcıya rol atanırken beklenmeyen bir hatayla karşılaşıldı.");
            return RedirectToAction("Index");
        }
    }
}

BenimProjem/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BenimProjem.BL.Business.Abstracts;
using BenimProjem.Entities.ViewModels.Urun;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BenimProjem.PL.Controllers
{
    public class UrunController : Controller
    {
        IUrunBusiness _urunBusiness;
        IKategoriBusiness _kategoriBusiness;

        public UrunController(IUrunBusiness urunBusiness, IKategoriBusiness kategoriBusiness)
        {
            _urunBusiness = urunBusiness;
            _kategoriBusiness = kategoriBusiness;
        }

        //if (kategoriId != null)
        //{
        //    urunler = _urunBusiness.AnasayfaKategoriyeGoreUrunListele(kategoriId.Value);
        //    ViewBag.KategoriAdi = _kategoriBusiness.KategoriGetir(kategoriId.Value) + "Ürünleri";
        //    return View(urunler);
        //}
        public IActionResult Index(int? kategoriId)
        {
            ViewBag.Kategoriler = _kategoriBusiness.Listele();
            List<AnasayfaUrunleriListeleVM> urunler = null;
            if (kategoriId != null)
            {
                urunler = _urunBusiness.AnasayfaKategoriyeGoreUrunListele(kategoriId.Value);
                ViewBag.KategoriAdi = _kategoriBusiness.KategoriGetir(kategoriId.Value) + "Ürünleri";
                return View(urunler);
            }
            else
            {
                ViewBag.KategoriAdi = "Ürünler";
                return View(_urunBusiness.AnasayfaUrunListele());
            }
        }
        public IActionResult KategoriUrunleri()
        {
            ViewBag.Kategoriler = _kategoriBusiness.Listele();
            return PartialView();
        }
    }
}

BenimProjem/Areas/yonetimPaneli/Views/Shared/_Layout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Anasahife</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    @*<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="color:gray">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-action="Index" asp-controller="Home" asp-area=""><strong>Anasahife</strong><span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="row">
        <div class="col-lg-3 ">
            <div class="list-group" style="margin-left:10px;margin-top:10px">
                <a class="list-group-item list-group-item-action" asp-action="Index" asp-controller="Urun">Urunler</a>
                <a class="list-group-item list-group-item-action" asp-action="Index" asp-controller="Kategori">Kategoriler</a>
                <a asp-action="Index" asp-controller="User" class="list-group-item list-group-item-action">Kullanıcılar</a>
                <a asp-action="Index" asp-controller="Role" class="list-group-item list-group-item-action">Roller</a>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="demo-content bg-alt">
                @RenderBody()
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
</body>
</html>